name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-dev \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-setuptools \
          python3-venv \
          git \
          zip \
          unzip \
          openjdk-8-jdk \
          zlib1g-dev
        pip install cython==0.29.28
        pip install buildozer
        pip install python-for-android

    - name: Build APK
      run: |
        buildozer -v android debug
      env:
        ANDROIDSDK: /usr/lib/android-sdk
        ANDROIDNDK: /usr/lib/android-ndk
